### ISSUE TITLE
TCW revisions not updating on website from Documentation repo

### ISSUE THREAD

**Issue by ebeshero** [TEIC/website#30]
I pushed some updates to TCW 22 today and notice that those updates aren't being pulled in to the website. Do we need a GitHub Action or some revision to [the scripts found here](https://github.com/TEIC/website/tree/main/src/documentation)?

We have two published web URLs for reading TCWs:
*  https://teic.github.io/Documentation/TCW/tcw22.html (reliably current, but step numbering isn't equivalent to website)
* https://tei-c.org/documentation/tcw22/  (not pulling in updates)

Here is a revision to look for:
On this website TCW 22 Step 19 still mentions updating the Wordpress website release table and going to me or Martina if people don't have edit access. I revised it to remove those details and point to the new website (where we all have edit access).

On the github.io publication of TCW22, the step about updating the website release table is numbered 22 (and reflects the new language).

**Comment by hcayless** [comment]
Fixed. Turns out you have to explicitly update submodules or they "stick" at the last time they got committed.
